### ISSUE TITLE
Share a clipboard

### ISSUE THREAD

**Issue by Fastidious** [jedisct1/piknik#11]
On the `README.md` you mention:

> Share a clipboard with your teammates (which can be a lot of fun)

How is that accomplished? Thanks!

**Comment by jedisct1** [comment]
Hi!

All you need is the same `piknik.toml` configuration, which can be automatically derived from a password if this is easier to share with your teammates.

**Comment by Fastidious** [comment]
Excellent, thanks @jedisct1!
