### ISSUE TITLE
Windows copy hangs

### ISSUE THREAD

**Issue by coolemet** [jedisct1/piknik#12]
Thank you for creating piknik!

I'm having an issue with "piknik.exe -copy" on Windows computers (W7 / XP). Copying of files is working fine but copying of Windows clipboard just hangs. Is there any prerequisites for piknik to work on Windows?
I'm using version 0.9.1 precompiled binaries.
Tried it on three computers with the same issue.
Could you please look into this.
Thanks

Here is what I see http://i.is.cc/m38KTaW.gif

**Comment by jedisct1** [comment]
Are you using Powershell or just CMD.EXE ?

**Comment by coolemet** [comment]
Just CMD.EXE.

**Comment by coolemet** [comment]
With Powershell, the issue is the same.

**Comment by jedisct1** [comment]
Did you try hitting Ctrl-D after having pasted the content?

**Comment by coolemet** [comment]
Ctrl-D does nothing in CMD/PowerShell.
If I hit Ctrl-Z (EOF) and then enter, that will produce "Sent" response and send empty space to the server.
If I type something before Ctrl-Z + Enter then that text will be send. 
It seems like piknik can't copy from clipboard.

**Comment by mattn** [comment]
CTRL-Z works well.

![shoei](https://user-images.githubusercontent.com/10111/35221590-097a1eca-ffbe-11e7-92cb-6461db4cc936.gif)
