### ISSUE TITLE
Multiple clipboard (slot) feature?

### ISSUE THREAD

**Issue by Ardakilic** [jedisct1/piknik#13]
Hello,

I was wondering if there are any plans for multiple clipboard feature, e.g: setting a slot for a copy, which defaults to zero for backward compatibility.

That way I believe It'll be more usable, at least will be for me.

Thanks for maintaining such a great app (and DNSCrypt, too!)

Cheers,

**Comment by jedisct1** [comment]
Yes! I've been busy with other projects, but this is definitely on the roadmap.

The idea is that people can register accounts (which will just upload their public key to the server, associated to a user name), and then anyone can send encrypted content to anyone just given their user name.

**Comment by jedisct1** [comment]
Sorry, I read your question a bit too fast :)

Multiple slots for a given user...

Not something that was initially planned, but why not!
Just wondering how integration with tools such as Visual Studio Code would look like.

**Comment by Ardakilic** [comment]
Hey there, sorry for the late reply.

Indeed, I was talking about multiple slots for a given user. Many people use various apps on their environments just for multiple clipboard / clipboard history feature. This brings not only that, but also makes it accessible anywhere regardless of the platform!

About the editor plugins, Maybe something like `Ctrl + Alt + Shift + 1(slot number/name)` and then pressing `C` (a similar behaviour like `tmux` or `screen` detaching) or `piknik:copy 1` as command *for when the slot parameter will be provided* ?

**Comment by andymass** [comment]
This would be pretty useful for editors such as vim which have not one but many "clipboards."

Similarly, it would be nice if generic meta-data for the stored clipboard data could be stored out-of-band.  vim supports multiple selection types (line, character, block) but this could be useful for other purposes as well (e.g., time at copy, formatting information).  Obviously, one could stuff this all into a json object and use piknik as-is, but slots and/or metadata seems a bit cleaner.
