### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by kimusan** [jedisct1/piknik#14]
I would love to see that this great app got proxy support of some sort. It would make it easier to use from corp networks where you are usually behind some sort of proxy.

**Comment by jedisct1** [comment]
Hi there!

Piknik doesn't use HTTP, so it would be difficult to make it work through a proxy.

It could be encapsulated into HTTP frames (and HTTPS wouldn't even be required here), but it's also nice to keep the current simplicity of the protocol.
