### ISSUE TITLE
piknik: command not found

### ISSUE THREAD

**Issue by dharan1011** [jedisct1/piknik#16]
I'm running a `Linux ip-172-31-10-169 4.4.0-1044-aws #53-Ubuntu SMP Mon Dec 11 13:49:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux` and install pikinik using
`go get github.com/jedisct1/piknik` and also exported the path.
But still I am getting a issue`piknik: command not found`. How do I resolve it

**Comment by jedisct1** [comment]
It's probably hidden in `~/go/bin/`. You can leave it here and add the path to your `PATH` variable, or copy it anywhere you want, since it doesn't have any dependencies.
