### ISSUE TITLE
Client/Server share psk/signpsk?

### ISSUE THREAD

**Issue by jungle-boogie** [jedisct1/piknik#24]
Hi Frank,

I'm taking a look at your other wonderful creations and seeing all the great stuff you create - THANK YOU.

So I think I'm reading the README correctly but maybe something is missing in it.

server:
`piknik -genkeys`
copy to .piknik.toml

client:
`piknik -genkeys`
copy to .piknik.toml
edit the connect IP address

start the server:
`piknik -server`

Attempt to retrieve something on client:
`piknik`
But I see this instead:
`The server rejected the connection - Check that it is running the same Piknik version or retry later`.

Do any parts of the keys need to be shared among the clients/servers? Reviewing the samples, I see both client and server share the same psk and signpsk. This all makes sense.

Would you be open to a PR, provided what I said above is accurate, to explain this in a little more detail?

Thanks!

**Comment by jedisct1** [comment]
Hi,

You only need to create the keys once.

After you typed `piknik -genkeys`, copy the `# Configuration for a server` part on the server, and the `# Configuration for a client` on clients.

Or if a server can also be a client to itself, copy the `# Hybrid configuration` part on the server instead.

**Comment by jungle-boogie** [comment]
Ah, okay. I was running the command separately on the client and host. It only needs to be ran on either the client or server.

**Comment by jedisct1** [comment]
Exactly.

Note that in spite on the pre-shared keys, the server doesn't know anything about what is being stored.

The pre-shared keys only act as an "acces code" to be able to use the API. This avoids wasting CPU cycles on web crawlers, scanners, and other clients sending junk that would not be stored anyway. It's also an extra security layer in case there is a vulnerability in the code.
