### ISSUE TITLE
Why a new release not public in long time?

### ISSUE THREAD

**Issue by kelunce** [jedisct1/piknik#26]
Why a new release not public in long time? 
the  release latest is in 2016, now

**Comment by jungle-boogie** [comment]
To be fair, building a go binary is pretty easy. I did it on OpenBSD and Windows without much effort.

**Comment by kelunce** [comment]
y,  so i need install my golang env.   make a release will help more people  to use easy

**Comment by jedisct1** [comment]
There hasn't been any new release because... there has been no need to?

Piknik works and does what it was designed to do. There are no bugs or vulnerabilities I'm aware of. The code still compiles and fine with current Go versions.
