### ISSUE TITLE
open /root/.piknik.toml: no such file or directory 

### ISSUE THREAD

**Issue by yuis-ice** [jedisct1/piknik#27]
After installation I got a error when I tried to run the executable `./piknik`. 

Following is entire installation commands on docker ubuntu 16.04. 

```
# install golang 

apt install software-properties-common
add-apt-repository ppa:longsleep/golang-backports -y 
apt-get update
apt-get install golang-go -y 

# install gvm, use gvm 

apt update ; apt-get install curl git mercurial make binutils bison gcc build-essential
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
source ${HOME}/.gvm/scripts/gvm

gvm install go1.12.9
gvm use go1.12.9 

# install piknik

git clone https://github.com/jedisct1/piknik.git
cd piknik
go build

```

Following is the error message. 

```
# ./piknik
open /root/.piknik.toml: no such file or directory
```

**Comment by jedisct1** [comment]
Read the [documentation](https://github.com/jedisct1/piknik/blob/master/README.md)?

**Comment by jedisct1** [comment]
Also, you should probably just use the precompiled binary.

What you did looks way too complicated and to be honest, I have no idea what all these command do and why you need to install so many unrelated dependencies.

**Comment by yuis-ice** [comment]
yes I have read.  and now I have read once again.

I have tried following one on ubuntu 18.04 not docker, installation with compiled binary, but as you can see, I got same error message.

```
go version
go version go1.12.9 linux/amd64
```
```
wget https://github.com/jedisct1/piknik/releases/download/0.9.1/piknik-linux_x86_64-0.9.1.tar.gz
cd linux-x86_64/
```
```
$ ./piknik
open /home/yuis/.piknik.toml: no such file or directory
```

**Comment by jedisct1** [comment]
You need to crate the file. https://github.com/jedisct1/piknik#setup

**Comment by yuis-ice** [comment]
oh. I have solved. thanks.
