### ISSUE TITLE
[protocol] ekid should be authenticated

### ISSUE THREAD

**Issue by dsprenkels** [jedisct1/piknik#28]
I am currently learning Tamarin, and as a case study I was looking at the Piknik protocol. There's seems to be a small gap in the security of the protocol.

Consider the very rare case that a network has a compromised encryptKey and a malicious server.

If a client receives a clipboard state from the server, then it should be authenticated by another (or the same) client. However, this is not the case, because the encryptKeyID corresponding to a ciphertext in the clipboard is malleable by the server. This way the server can force decryption under an old key (if the client hasn't updated its key yet), resulting in a garbled plaintext.

This is fixable by having the clients also sign the ekid, during a Copy operation. I.e. `s := Sig(n || ct, ekid)`.

Obviously this is a **very rare** case, and will probably not really happen in practice.

-----

Tamarin file: https://gist.github.com/dsprenkels/0e858ea6fc1b8500571f3b91f8badd2d (disclaimer: very ugly non-public amateur code)

**Comment by jedisct1** [comment]
Hi,

And sorry for the delay. I wasn't watching the repository and only stumbled upon your message by accident today.

Thanks and modeling the Piknik protocol with Tamarin! This is great!

The protocol has been slightly changed to include `ekid` in the signature.

Thanks again!

**Comment by dsprenkels** [comment]
No problem. :)
