### ISSUE TITLE
piknik on mobile (iOS, Android)?

### ISSUE THREAD

**Issue by jpmens** [jedisct1/piknik#3]
Now that I'm addicted to _piknik_: is there any chance of getting this for mobile (Android, and in particular iOS)? This would be a great way to transport passwords/passphrases etc. without cloud usage.

Consider this a feature request. 😃 

IMO the UI could be very "primitive": a `-copy` would literally copy from clipboard and a `-paste` to clipboard.

**Comment by jedisct1** [comment]
That would be great!

The core can easily be compiled for iOS and Android (or rewritten using libsodium), but I don't think I'll be able to find enough spare time to work on the actual apps in a foreseeable future :(

**Comment by Sidetalker** [comment]
If there's any public interest, I might spin something up for iOS.

**Comment by jedisct1** [comment]
@Sidetalker That would awesome!

Lemme know if you need any help with the protocol.

**Comment by Sidetalker** [comment]
Thanks guys, I'll comment again this weekend when I spin something up - it'll be public, so feel free to contribute @chrishorton! I had a helluva a time trying to get ports opened up on my Windows machine (planning to use as my server) last night and ended up dropping it (I only had 30-60 minutes to work on it). I plan to follow up this evening / over the weekend.

**Comment by Sidetalker** [comment]
Hey everyone, I've been trying to get piknik compiled as an iOS framework and have run into a blocker... maybe someone in here can help out?

I'm using `gomobile` and was able to get the "Getting Started" example working with no problem. 

To get piknik compiled, I first needed to move it out of `package main`. I did this in two different ways over in my cloned repo - the more straightforward one is https://github.com/Sidetalker/piknik/tree/ios-prep-v2.

`gomobile` now has a package from which to build the framework, but unfortunately it seems `uint64` isn't supported:
```
> gomobile bind -v -target ios core
gomobile: unsupported basic type: uint64
```

At this point I started digging around in the `gomobile` project. It looks like `uint64` support is missing due to Java's inherent lack of unsigned support. I don't actually care about Java/Android for this project, so I started editing files pretty hackily to try to get it to build for iOS... I was able to get it further along, but not quite to the finish line:

```
Kevins-MacBook-Pro:piknik-core kevin$ gomobile bind -v -target ios core
write /var/folders/by/5n848f_14b1c1pv7y4dtsq280000gn/T/gomobile-work-036389928/src/gomobile_bind/interfaces.go
write /var/folders/by/5n848f_14b1c1pv7y4dtsq280000gn/T/gomobile-work-036389928/gen/src/ObjC/interfaces.go
write /var/folders/by/5n848f_14b1c1pv7y4dtsq280000gn/T/gomobile-work-036389928/src/gomobile_bind/interfaces.h
write /var/folders/by/5n848f_14b1c1pv7y4dtsq280000gn/T/gomobile-work-036389928/src/gomobile_bind/interfaces.m
github.com/BurntSushi/toml
github.com/mitchellh/go-homedir
golang.org/x/crypto/ed25519/internal/edwards25519
github.com/yawning/chacha20
github.com/minio/blake2b-simd
golang.org/x/crypto/pbkdf2
golang.org/x/sys/unix
golang.org/x/crypto/scrypt
golang.org/x/crypto/ed25519
golang.org/x/crypto/ssh/terminal
core
write /var/folders/by/5n848f_14b1c1pv7y4dtsq280000gn/T/gomobile-work-036389928/fakegopath/pkg/darwin_arm/core.a
write /var/folders/by/5n848f_14b1c1pv7y4dtsq280000gn/T/gomobile-work-036389928/src/gomobile_bind/go_coremain.go
gomobile: unsupported basic type: uint64
```

This is where I'm at now. Taking a break, but I'll definitely revisit. At this point I'd probably save time by reimplementing the spec natively, but I really want to get the existing Go code compiled for iOS because there's not technical reason I shouldn't be able to!

**Comment by Sidetalker** [comment]
There should be a way to short-circuit the Java-specific code that's blocking the build, I just don't have enough experience with Go to get it working. 

That string only appears in [two error messages through the go files](https://github.com/golang/mobile/search?utf8=✓&q=unsupported+basic+type&type=). The progress I made was through adding cases to those switch statements, and more recently (also unsuccessfully) returning something before the error message would even print. I did make a little more progress because I observed that the error message still printed, meaning there's something wrong with my understanding of the build process here. I don't quite get how my changes resulted in different output, but the code I added returning right before the error statement still results in the error statement being printed. Any idea?

**Comment by Sidetalker** [comment]
Progress! I theorized that `go get` was doing some pre-compiling that `gomobile init` didn't cover, and was proven correct. I've cloned the whole `gomobile` project and am fully applying my hacky modifications by `go get`ing [my own repo](https://github.com/Sidetalker/mobile).

I just hit this

```
> gomobile bind -target ios core
gomobile: unsupported const type byte for DefaultClientVersion
```

Now I've got to find out why that support is missing and add more hacks 💯

**Comment by Sidetalker** [comment]
Alright, a few more commits in the [my hacky repo](https://github.com/Sidetalker/mobile) and I've got a `.framework`!

However, I was super bummed out to find these two comments in the generated header:
```
// skipped function RunClient with unsupported parameter or return types
// skipped function RunServer with unsupported parameter or return types
```

The investigation continues.

@chrishorton the iOS repo has been created! https://github.com/Sidetalker/piknik-ios

**Comment by Sidetalker** [comment]
Success 🎉 

My iOS app now launches, prints the following, and immediately crashes
```
open /Users/kevin/Library/Developer/CoreSimulator/Devices/1E3111DA-80FE-4D0E-9112-AEC24F58D4F5/data/Containers/Data/Application/5EA72827-81B1-4C27-9904-BC42E6DB78CB/.piknik.toml: no such file or directory
```

This is a massive win in my book - now all I need to do is programmatically generate my `.piknik.toml` and we should be cooking with fire! I'll check back in when I've got an iOS client that's functional, but I'm past the major obstacles!

**Comment by Sidetalker** [comment]
@jedisct1 I'm have my `~/.piknik.toml` configured for hybrid mode on my Mac, but when I try to paste with `piknik -paste` the command just hangs forever. I have `piknik -server` running in another terminal - is this a proper use of hybrid mode?

**Comment by Sidetalker** [comment]
@jedisct1 I have `~/.piknik.toml` configured for hybrid mode on my Mac, but when I try to populate the piknik clipboard with `piknik -copy` the command just hangs forever. I have `piknik -server` running in another terminal - is this a proper use of hybrid mode?

**Comment by Sidetalker** [comment]
Alright, progress report as I don't think I'm going to spend any more time on this unless I get some help. I seem to be having some fundamental issues with getting `piknik` working on regular machines using the official build. I think my router's port forwarding might be defective, and I also can't seem to get the hybrid mode working so I could just test completely locally.

Those problems aside, I think I've got piknik to a somewhat functional state within an iOS framework. 

You can see the changes I've made so far to `piknik` in the `ios-prep-v2` branch of this repo: https://github.com/Sidetalker/piknik/tree/ios-prep-v2
It's just been a lot of shuffling around code to make it usable as an iOS framework. 

My other iOS repo has `piknik` included as `Core.framework`: https://github.com/Sidetalker/piknik-ios

I think it might actually be functional, I just can't test it myself! @chrishorton if you could play around with this it would be awesome!

Unfortunately I haven't set up an easy way to generate `Core.framework`. If you need to make changes to `piknik`, you'll have to adapt my current build process
```
go build core
gomobile bind -target ios core
```

Setting up the pre-reqs is a massive PITA considering how strewn about they are - if someone submits a pull request to my `piknik` repo and requests I build them a `Core.framework` based off it I can do so.

**Comment by jedisct1** [comment]
@Sidetalker Did you hit Ctrl-D after running the command? Or you can use `echo xyz | piknik -copy`.

I can quickly set up a public Piknik server if it can help.

**Comment by Sidetalker** [comment]
Hah, derp, that works just fine - for some reason I thought `piknik` would be grabbing my clipboard, but that type of use is totally covered in your aliases. Alright, we're cooking with fire again.
```
> echo xyz | piknik -copy
Sent
> piknik
xyz
```

Thanks @jedisct1!

**Comment by Sidetalker** [comment]
I quickly hit another blocker... Now on my iOS client I get the following output. I'm going to dig around in the source to see if I can short-circuit this version checking, but if you have any pointers they'd be appreciated.
```
The server rejected the connection - Check that it is running the same Piknik version or retry later
```

**Comment by jedisct1** [comment]
Is the server port open and accessible from that device?

**Comment by Sidetalker** [comment]
Yes, I'm running the iOS simulator so I just have everything talking to 127.0.0.1:8075. Works in the terminal which is the same device, just a custom piknik build.

**Comment by Sidetalker** [comment]
@jedisct1 I was able to get a generic TCP client running on iOS and can confirm that I can connect to the server and successfully send it data.

**Comment by jedisct1** [comment]
Damn :(

In case you want to test with an external server:

```toml
Connect   = "94.23.199.27:8075"
Psk       = "29e72ddf1b019fd13d8285c57fe266e4595af1ba284e5ccf8da5fb64e932ef64"
SignPk    = "a467f8c866fb82d75ed232edfafb880db260163975ef092ba3246f4e4121d52a"
SignSk    = "fdb48682f83ec502233b225c907fe8896c93a15260cf01a348d0bb9b4ea80942"
EncryptSk = "af4bb6e42eb61ad95a6bb2bb99f89d6b0dba20dfcb15d4f9a9bdbee7ee115fbb"
```

**Comment by Sidetalker** [comment]
Interesting, using your that server the copy command seems like it may be successful, but my modified code doesn't have a way to send input to the function right now.
```
2018-01-20 14:04:09.660735-0500 Piknik[84756:3416787] Returning local object of class NSString
2018/01/20 14:04:09 <nil>
```
However the paste functionality should be able to return a string... I'm getting another different error now when running paste. I think this may be a bug that I introduced in shuffling code around...
```
2018/01/20 14:06:35 write tcp 192.168.1.221:61259->94.23.199.27:8075: use of closed network connection
```

**Comment by Sidetalker** [comment]
I'm not sure why the server you provided doesn't reject my client's connection but my local server installed via `brew` does - any clue?

**Comment by jedisct1** [comment]
Is it the same version (0.9.1)?

**Comment by jedisct1** [comment]
The connection can also be prematurely closed if the `Psk` doesn't match.

**Comment by Sidetalker** [comment]
Thanks @jedisct1 - it is the same version `Piknik v0.9.1 (protocol version: 5)`. Still playing with other things, at this point I need to figure out what's up with that tcp error.

**Comment by Sidetalker** [comment]
Unfortunately there are signs that it may be a bug with Go itself that has made it into the code produced by `gomobile`: https://github.com/golang/go/issues/21760

Regardless, this has been a really fun learning experience.

**Comment by jedisct1** [comment]
Ouch :((((((

**Comment by dharan1011** [comment]
I would love to work on `Android` version of `piknik`. Any interests ?

**Comment by Sidetalker** [comment]
@dharan1011 I'm interested! Have you read through this whole thread? Right now the main blocked for Java is the lack of unsigned types, meaning the Go code that `piknik` is written in cannot be compiled for Java. What are your plans to get past that hurdle and how can I help you such that the hurdle is crossed for iOS at the same time?

**Comment by dharan1011** [comment]
Yeah. I have been through the whole thread, also noticed the lack of `unsigned types` in java. I am hacking on it to get through it, any point I get the solution I will discussing here on thread.
Here is my contact info @ [Dharan Aditya](dharan.aditya@gmail.com)

**Comment by chrishorton** [comment]
@suedadam any chance you could take a look at the compatibility issues?

**Comment by Sidetalker** [comment]
We’ve got a pretty good grasp on the issues - at this point I think Piknik needs to rewritten in something appropriate for Android/iOS. iOS support might be possible by tweaking the existing code, but I don’t think we’re going to see android support that way.
