### ISSUE TITLE
is a  piknik server running on that host?

### ISSUE THREAD

**Issue by ariagecheney** [jedisct1/piknik#31]
hello! I come from china ,and have a local MAC and a remote Linux server.
1 on my MAC, 
run:   brew install piknik, 
run : piknik-genkeys,      
copy client part to ~ /.piknik.toml  such as 

 # Configuration for a client
Connect   = "127.0.0.1:8075"	# Edit appropriately
Psk       = "7fd5aff6e7b473d3b0d8699923b7133261afff2b635cd20e9624b79eb0a93479"
SignPk    = "f2076dc18a1c24e50d85b95c558d5800079e2c56ac4099bd84c5d26a6933129a"
SignSk    = "a1eee78ef0c77abbcc255376f275afbbc680138d57936122323842e0a6e62073"
EncryptSk = "556ad73c49bc73cd06a3faf18be65ac85f902ed34522438cb7be0c9d73b97c76"

-------------------------------------------------------------------------------------
# Configuration for a server

Listen = "0.0.0.0:8075"	# Edit appropriately
Psk    = "7fd5aff6e7b473d3b0d8699923b7133261afff2b635cd20e9624b79eb0a93479"
SignPk = "f2076dc18a1c24e50d85b95c558d5800079e2c56ac4099bd84c5d26a6933129a"

2 on a Linux server, 
run : 
wget https://github.com/jedisct1/piknik/releases/download/0.9.1/piknik-linux_x86_64-0.9.1.tar.gz, 
put the server configuration  part   on  linuxserver: ~ /. piknil. toml, 
run : piknik  -server

3 but i get an error:
"is a  piknik server running on that host?"!

4   My English is not very good and I don't quite understand the confitgure of READ.md between mac and linux or windows.  

5   May you  release piknik for Android  ?i hope that .

**Comment by jedisct1** [comment]
`Connect = "127.0.0.1:8075" # Edit appropriately`

You need to replace `127.0.0.1` with the server IP address.
