### ISSUE TITLE
Latest release doesn't include binaries.

### ISSUE THREAD

**Issue by vpicone** [jedisct1/piknik#35]
The `0.10.1` release only includes source code, not the binaries https://github.com/jedisct1/piknik/releases/tag/0.10.1

A the moment, this is causing the docker image (which downloads from the release URL) to fail. (https://github.com/vimagick/dockerfiles/issues/173)

**Comment by jedisct1** [comment]
They have been added, thank you!

These used to be automatically built, but Travis doesn't support oensource projects any more.
