### ISSUE TITLE
piknik not work in Ubuntu keyboard shortcuts

### ISSUE THREAD

**Issue by ArtisticZhao** [jedisct1/piknik#36]
Hi,
Thank you for create this useful tool.

But I want to use this which one shortcuts in Ubuntu 18.04
I drop commands below in the shortcuts settings.
```
sh -c " sleep 0.5 && xdotool key Control_L+Insert && xclip -sel c -o > /tmp/t && xclip -sel c -o | piknik -copy"
```
![2021-09-09_19-32](https://user-images.githubusercontent.com/22850287/132678431-ea02afca-2bba-4941-a2fd-b646876c4f44.png)

By press super+C with select some text in chrome, I can find the `xclip -sel c -o > /tmp/t` put the selection to the file. But piknik seems not be trigger.

Any ideas?

**Comment by jedisct1** [comment]
Hi!

Maybe the `piknik` command is not in your `PATH`, or the path that is available for shortcut commands?

I don't use Linux, so unfortunately I can't really help with this.

**Comment by ArtisticZhao** [comment]
Hi,
You are right, I use the Linuxbrew to install the piknik. It can work in my shell but not work for the Gnome keyboard shortcut.
So, my solution is create a softlink to `/usr/bin/`.

p.s. My shortcut configuration is:
```
# Super+C to copy current context to piknik
sh -c " sleep 0.5 && xdotool key Control_L+Insert && xclip -sel c -o > /tmp/t && xclip -sel c -o | piknik -copy"

# Super+V to paste from piknik
sh -c "sleep 0.5 && piknik -paste | xclip -i -selection c && xdotool key Shift_L+Insert"
```
It needs `xclip` and `xdotool` to installed.

And appreciate for the wandful tool.
