### ISSUE TITLE
Hex Error

### ISSUE THREAD

**Issue by iliesh** [jedisct1/piknik#37]
Isn't working for me, getting an error on the client while I'm trying to copy something:

```
~/linux-x86_64$ echo "test_copy" | /usr/local/bin/piknik -copy
encoding/hex: invalid byte: U+005E '^'

~/linux-x86_64$ /usr/local/bin/piknik -version
Piknik v0.10.1 (protocol version: 6)
```

Ubuntu 21.04

**Comment by jedisct1** [comment]
Hi!

It means that your `piknik.toml` configuration file contains unexpected characters.

Maybe you can recreate one with `picnic -genkeys`, or make sure that you didn't unintentionally type weird characters while editing it.

**Comment by iliesh** [comment]
Hi,
Yes, you're right. I don't know how an extra symbol appeared to the EncryptSk key. After I deleted it - started to work as supposed.
Thank you.
