### ISSUE TITLE
stderr for diagnostics / status?

### ISSUE THREAD

**Issue by jpmens** [jedisct1/piknik#5]
`piknik -copy`, `-zero`, etc. print a "success" message on _stdout_:

```bash
echo hello | pkc 2> /dev/null
Sent
```

Wouldn't these be more suited for _stderr_?

**Comment by jpmens** [comment]
Actually, in good Unix tradition: shouldn't the `Sent` be omitted entirely upon success? :-)

**Comment by jedisct1** [comment]
I kinda like a little feedback on success, especially for a destructive command (that overwrites something). But maybe a `-quiet` option can be added to remain silent.

`stderr` may indeed be a better fit. Gonna change that right away. Thanks!

**Comment by jedisct1** [comment]
Changed in 9e128da26f8bee95f8e09c398ba586dede03015d

Thanks!
